config/routes.rb
require "resque/server"

Heat4us::Application.routes.draw do

  root :to => 'index#index'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signin' => 'sessions#new', :as => :signin

  match '/heatmap' => 'heatmaps#index'

  resources :heatmaps, :only => [:new] do
    collection do
        get :new_screenshot
    end
  end

  mount Resque::Server.new, :at => "/resque"

end

app/models/user.rb
class User
  include Mongoid::Document

  field :provider, type: String
  field :uid, type: String, required: true
  field :name, type: String

  def self.find_or_create_omniauth(auth, current_user = nil)
    auth_info = auth['info']
    uid = auth_info['email']

    user = current_user || User.where(:uid => uid).first || new(:uid => uid)
    user.name = auth_info['name']
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :user_signed_in?

  private

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Mongoid::Errors::DocumentNotFound
      reset_session
      nil
    end
  end

  def user_signed_in?
    !!current_user
  end

  def login_required!
    unless current_user
      redirect_to signin_url
    end
  end
end

app/controllers/heatmaps_controller.rb
class HeatmapsController < ApplicationController

  def new
    user_id = request.params['id']
    dt = request.params['dt'].to_i / 1000
    width = request.params['w'].to_i
    height = request.params['h'].to_i
    height = request.params['h'].to_i
    url = request.params['l']

    clicks = request.params['cl'] || ''
    hovers = request.params['ho'] || ''
    scrolls = request.params['sc'] || ''

    Resque.enqueue(Heatmap, user_id, url, dt, width, height, clicks, hovers, scrolls)
    render :text => "h4.tracker.callback('#{ request.params['dt'] }');"
  end

  def new_screenshot
    Resque.enqueue(Screenshot, "http://www.globo.com")
    render :text => "ok"
  end

  def index
    tracking = 'hovers'
    hour_prefix = Time.now.strftime('%Y-%m-%d-%H')
    list_key = "#{ current_user.id }-#{ hour_prefix }-list-#{ tracking }"
    @list = $redis.smembers(list_key)

    @list.map! do |item|
      keys = item.split('-')
      quadrant = keys[-2].to_i

      data = $redis.get(item)
      { :quad => quadrant, :count => data }
    end
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_or_create_omniauth(auth, current_user)
    session[:user_id] = user.id
    redirect_to request.env['omniauth.origin'] || root_url, :notice => "Signed in!"
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def new
    redirect_to '/auth/google_oauth2'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heatmaps_helper.rb
module HeatmapsHelper
end

app/views/heatmaps/index.html.erb
<div id="heatmap">
  <% 25.times do %>
      <p><% 20.times do %>lorem ipsum dolor sit amet<% end %></p>
  <% end %>
</div>

<script src="/assets/heatmap.js?body=1" type="text/javascript"></script>
<script src="/assets/heatmap_viewer.js?body=1" type="text/javascript"></script>
<script>
  heat4us.tracker.plot(document.getElementById('heatmap'), [
      <% for item in @list%>
      { quad: <%= item[:quad] %>, count: <%= item[:count] %>},
      <% end %>
  ]);
</script>

app/views/index/index.html.erb
<div id="main-content">

  <div id="first-section">

    <% unless user_signed_in? %>
      <%= link_to 'login', signin_path, :class => 'login-btn' %>
    <% end %>

    <div class="top-area">
      <div class="flamee"></div>
      <ul>
        <li class="current">Home</li>
        <li><a href="#">Features</a></li>
        <li><a href="#">Examples</a></li>
        <li><a href="#">Documentation</a></li>
        <li><a href="#">Support</a></li>
      </ul>
    </div>

    <div class="carousel">
      <ul class="pages">
        <li>
          <span class="first-line">Know what your users are doing with</span>
          <span class="second-line">powerful heatmaps</span>
          <span class="third-line">showing their web experience.</span>

          <span class="info">
            DISCOVER FIRST-HAND what areas of your website actually matter with our reports. HEATMAPS THAT show your users INTERACTIONS. Scroll MAP that shows what portions they are SEEING. <a class="more-info" href="#"></a>
          </span>
        </li>
        <li>
          <span class="second-line">something else!!</span>
        </li>
        <li>
          <span class="second-line">yet another</span>
        </li>
      </ul>

      <div class="pagination">
        <!-- Inline-block element, plz avoid spaces -->
        <a href="#" class="current"></a><a href="#"></a><a href="#"></a>
      </ul>
    </div>




    <% if user_signed_in? %>
      <div id="heatmap">
        <% 25.times do %>
            <p><% 20.times do %>lorem ipsum dolor sit amet<% end %></p>
        <% end %>
      </div>
      <script src="/h4.js"></script>
      <script>
        h4.tracker.initialize('<%= current_user.id %>');
      </script>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heat4us</title>
  <%= stylesheet_link_tag "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>